spring:
  datasource:
    username: root
    password: pmalviya
    url: jdbc:mysql://localhost:3306/dbdesign
    driverClassName: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true